### ISSUE TITLE
[공통] 백드롭 모달 컴포넌트 구현

### ISSUE THREAD

**Issue by elenfl0122** [Tea-Bliss/FE_Tea_Bliss#3]
### 📌 기능설명

- 백드롭 모달 컴포넌트 구현

### 📌 ToDo
- 어떤거 구현할지 체크박스 형태로
- [ ]   버튼 클릭 시 모달 생성
- [ ] 모달 제외한 뒷배경 어둡게 구현
- [ ] 모달 생성 시 뒷배경 스크롤 제한되도록 구현
- [ ] 모달 제외한 뒷배경 클릭 시 모달 닫히도록 구현
