### ISSUE TITLE
[공통] 글로벌 css 파일 생성

### ISSUE THREAD

**Issue by Jin-Chanyong** [Tea-Bliss/FE_Tea_Bliss#5]
### 📌 기능설명

- 기본 globals.scss 파일 생성 및 레이아웃 파일에 적용

### 📌 Screenshot

- 자기가 구현할거 피그마 시안 캡쳐

### 📌 ToDo

- [x] 기본 리셋용 css 파일 적용
- [x] 사전에 사용하기로 한 mixin css 파일 생성
- [x] 기본 폰트 적용

### 🤔 ETC[선택]

- 기타사항! (특별히 전달할 내용 or 질문 등등)
</aside>
