### ISSUE TITLE
[공통] GNB 컴포넌트 구현

### ISSUE THREAD

**Issue by hsmurf** [Tea-Bliss/FE_Tea_Bliss#9]
### 📌 기능설명

- GNB 컴포넌트 구현

### 📌 Screenshot

![image](https://github.com/Tea-Bliss/FE_Tea_Bliss/assets/107796704/a60beed6-dcf0-41a7-9dc9-57e5f851a934)

### 📌 ToDo

- [x]  비 로그인 상태 UI 
- [x] 로그인 상태 UI
- [x] 모바일 일때 UI
- [x] 프로필 이미지 클릭 시 내 정보 보여줄 팝오버

### 🤔 ETC[선택]

- 기타사항! (특별히 전달할 내용 or 질문 등등)
</aside>
